### ISSUE TITLE
max retries of an algorithm should fail the pipeline

### ISSUE THREAD

**Issue by eytangro** [kube-HPC/hkube#146] opened 2018-05-30 13:08 UTC
if running an algorithm and the worker pod running the algorithm keeps failing, when reaching a configurable number of fails the pipeline should be failed and a proper message should be shown as the error.
this feature dosent work and the pipeline just keeps running and trying to finish the algo.

**Comment by maty21** [comment] 2018-07-29 11:54
duplicate of #17

**Closed by maty21** 2018-07-29 11:54 UTC
Labels: bug, duplicate, pipeline-driver, worker
