### ISSUE TITLE
Allow defining TTL in Algorithm/Node level

### ISSUE THREAD

**Issue by golanha** [kube-HPC/hkube#342] opened 2019-05-30 06:20 UTC

**Comment by yehiyam** [comment] 2020-01-27 08:41
duplicate of #601

**Closed by yehiyam** 2020-01-27 08:41 UTC
Labels: Type: Feature

**Comment by tamir321** [comment] 2020-04-19 07:13
#Algorithm TTL test
File: algorithm_tests.js
describe : "TID 480 - Test Algorithm ttl (git 61 342)"

Test | description 
------|----------------
ttl = 3 one of the inputs = 5 seconds | execute algorithm with ttl 3 seconds and duration 5 seconds
ttl =0 one of the inputs = 5 seconds | execute algorithm with ttl=0 ( no error )
