### ISSUE TITLE
DVC client fails to move files

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#1300] opened 2021-06-20 14:01 UTC
**HKube micro-service**
To which micro-service the bug related to, `Dashboard` ,`Monitor-Server` etc.

**Describe the bug**
DVC client fails to move files - the bug in the DVC client package code

**Expected behavior**

**To Reproduce**

**Screenshots**

**Additional context**

**Comment by yehiyam** [comment] 2021-06-21 05:37
duplicate of #1299

**Closed by yehiyam** 2021-06-21 05:37 UTC
Labels: HKube: Datasources, Type: Bug
