### ISSUE TITLE
hkubectl - watch and sync a- algorithm fail to reconnect to worker

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#1286] opened 2021-06-06 11:33 UTC
**HKube micro-service**
To which micro-service the bug related to, `Dashboard` ,`Monitor-Server` etc.

**Describe the bug**
hkubectl - watch and sync a- algorithm fail to reconnect to worker

**To Reproduce**
execute :

-  hkubectl sync create --entryPoint main.py --algorithmName <algorithim name> --folder <folder name> --env python

-   kubectl sync watch -a <algorithim name> -f <folder name>

- run the algorithm - should complete secssfuly 

- change the main.py  (the code was chage in the pod)

- rerun the algorithm  - the algorithm stay in active mode  and never excuted

**Comment by yehiyam** [comment] 2021-06-29 14:22
duplicate of #1314

**Closed by yehiyam** 2021-06-29 14:22 UTC
Labels: Type: Bug
